routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');


Route::get('/ajax', 'AjaxController@view');
Route::post('/ajax', 'AjaxController@send_http_request')->name('ajaxRequest.post');

Route::get('/getClientes', 'AjaxController@getClientes')->name('getClientes');
Route::post('/postClientes', 'AjaxController@postClientes')->name('postClientes');



Route::get('clientes/nomeTelefone', 'ClienteController@listNomeTelefone')->middleware('auth');
Route::get('clientes/nomeEndereco', 'ClienteController@listNomeEndereco')->middleware('auth');

Route::get('clientes/checkCEP', 'ClienteController@checkCEP')->middleware('auth');

Route::get('clientes/buscarNomeForm', 'ClienteController@buscarNomeForm')->middleware('auth');
Route::get('clientes/buscarNome', 'ClienteController@buscarNome')->middleware('auth');

Route::post('clientes/buscarNomeTelefone', 'ClienteController@buscarNomeTelefone')
            ->name('clientes.buscarNomeTelefone')->middleware('auth');
Route::post('clientes/buscarNome', 'ClienteController@buscarNome')
            ->name('clientes.buscarNome')->middleware('auth');          
            
            

Route::resource('cidades','CidadeController')->middleware('auth');

Route::resource('bairros','BairroController')->middleware('auth');

Route::resource('clientes','ClienteController')->middleware('auth');

Route::resource('contatos','ContatoController')->middleware('auth');

Route::resource('enderecos','EnderecoController')->middleware('auth');

/* quick and dirty
// dump sql query
// veja:https://stackoverflow.com/questions/27753868/how-to-get-the-query-executed-in-laravel-5-dbgetquerylog-returning-empty-ar
\Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {
    echo'<pre>';
    var_dump($query->sql);
    var_dump($query->bindings);
    var_dump($query->time);
    echo'</pre>';
});
*/

app/Contato.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contato extends Model
{
    protected $primaryKey = 'id_contato';
    protected $fillable = [
        'cliente_id_cliente','ddd','telefone'
    ];
    public $timestamps = false;
}

app/Http/Controllers/ContatoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ContatoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {                                          
        $contatos = DB::table('contatos')
                   ->join('clientes','contatos.cliente_id_cliente','=','clientes.id_cliente') 
                   ->select('contatos.id_contato','contatos.ddd','contatos.telefone','contatos.cliente_id_cliente','clientes.nome')
                   ->orderBy('clientes.nome')                                  
                   ->paginate(10);                         
        return view('contato.index', ['contatos' => $contatos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {          
       //$latest = DB::table('clientes')->orderBy('id_cliente', 'DESC')->first();
       $clientes = DB::table('clientes')
                         ->select('nome','id_cliente')
                         ->orderBy('nome', 'asc')
                         ->get();       
       return view('contato.create')->with(array('clientes'=>$clientes));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {                         
        // get hidden id_cliente if defined
        $hidden = $request->request->get('hidden');       
        $validatedData = $request->validate([              
            'cliente_id_cliente' => 'required|numeric',
            'ddd' => 'nullable',
            'telefone' => 'nullable'            
        ]
        ,['Favor, escolher cliente!']       
        );
  
        $show = \App\Contato::create($validatedData);   
       
        // voltar para show
        if (!is_null($hidden)) {
            return redirect('/clientes/'.$hidden);
        }
        // voltar para contato.index
        return redirect('/contatos')->with('success', 'Contato foi gravada');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {                           
        $clientes = DB::table('clientes')
                         ->select('nome','id_cliente')
                         ->orderBy('nome', 'asc')
                         ->get();      
        $selectedCliente = DB::table('contatos')
                         ->select('cliente_id_cliente')                          
                         ->where('id_contato',$id)
                         ->first()->cliente_id_cliente;
                         
        $contato = \App\Contato::where('id_contato', $id)->first();       
        return view('contato.edit', compact('contato'))
                     ->with(array('clientes'=>$clientes))
                     ->with(array('selectedCliente'=>$selectedCliente));           
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {      
        $validatedData = $request->validate([
            'cliente_id_cliente' => 'required|numeric',
            'ddd' => 'nullable',
            'telefone' => 'nullable'              
        ]
        ,['Favor, escolher cliente!']       
        );
        $ddd = $validatedData["ddd"];
        $telefone = $validatedData["telefone"];
        $cliente_id_cliente = $validatedData["cliente_id_cliente"];  
      
        DB::table('contatos')
            ->where('id_contato', $id)
            ->update(['cliente_id_cliente' => $cliente_id_cliente,'ddd' => $ddd,'telefone'=>$telefone]);
                        
        return redirect('/contatos')->with('success', 'Contato foi alterada');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {                
        DB::table('contatos')
            ->where('id_contato', $id)
            ->delete();       
        return redirect('/contatos')->with('success', 'Contato foi deletada');
    }
}

resources/views/contato/create.blade.php
@extends('components.layout')
@section('header')
<div style="font-size:xx-large;color:white;margin-right:50%;">
   <span>Contatos&nbsp;cadastrar</span>
</div>
@endsection
@section('content')
<style>
   .uper {
   margin-top: 40px;
   }
</style>
<div class="card uper">
   <div class="card-header">
      SAC - adicionar contato
   </div>
   <div class="card-body">
      @if ($errors->any())
      <div class="alert alert-danger">
         <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
         </ul>
      </div>
      <br />
      @endif
      <!-- // determinar de onde o arquivo foi chamado ( Novo Cliente | listar->adicionar ) -->   
      @php
      $url = session()->all()['_previous']['url'] ;
      $fromNovoCliente = strpos( $url,'clientes') != false ; 
      $cliente_id = Str::after($url,'clientes/') ;
      @endphp 
      <form  method="post" action="{{ route('contatos.store') }}">
         <div class="input-group mb-3">
            @csrf
            <!-- passar id do novo cliente ao contato.store -->
            @if($fromNovoCliente)
            <input name="hidden" type="hidden" value="{{ $cliente_id }}"/> 
            @endif
            <select class="custom-select" id="cliente_id_cliente" name="cliente_id_cliente">
               <option selected>Escolher cliente...</option>
               @foreach ($clientes as $cliente)
               <!-- marcar novo cliente -->
               <option 
               @if($fromNovoCliente && ($cliente->id_cliente == $cliente_id)) selected  @endif 
               value="{{ $cliente->id_cliente }}">{{ $cliente->nome }}</option>               
               @endforeach
            </select>
         </div>
         <div class="form-group">              
            <label for="ddd">DDD:</label>
            <input type="text" class="form-control" name="ddd" id="ddd"  maxlength="2" onkeypress="return isNumberKey(event)"/>
         </div>
         <div class="form-group">              
            <label for="telefone">Telefone:</label>
            <input type="text" class="form-control" name="telefone" id="telefone" maxlength="9" onkeypress="return isNumberKey(event)"/>
         </div>
         <button type="submit" class="btn btn-primary">Adicionar</button>
      </form>
   </div>
</div>
@endsection

resources/views/contato/edit.blade.php
@extends('components.layout')
@section('header')
<div style="font-size:xx-large;color:white;margin-right:50%;">
   <span>Contatos&nbsp;editar</span>
</div>
@endsection
@section('content')
<style>
   .uper {
   margin-top: 40px;
   }
</style>
<div class="card uper">
   <div class="card-header">
      Editar Contato
   </div>
   <div class="card-body">
      @if ($errors->any())
      <div class="alert alert-danger">
         <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
         </ul>
      </div>
      <br />
      @endif
      <form method="post" action="{{ route('contatos.update', $contato->id_contato ) }}">
         <div class="input-group mb-3">
            @csrf
            @method('PATCH')
            <select class="custom-select" id="cliente_id_cliente" name="cliente_id_cliente">
               <option selected>Escolher cliente...</option>
               @foreach ($clientes as $cliente)
               <option  @if($selectedCliente == $cliente->id_cliente) selected @endif
               value="{{ $cliente->id_cliente }}">{{ $cliente->nome }}</option>
               @endforeach
            </select>
         </div>
         <div class="form-group">              
            <label for="ddd">DDD:</label>
            <input type="text" class="form-control" name="ddd" id="ddd"  
               value="{{ $contato->ddd }}"
               maxlength="2" onkeypress="return isNumberKey(event)"/>
         </div>
         <div class="form-group">              
            <label for="telefone">Telefone:</label>
            <input type="text" class="form-control" name="telefone" id="telefone"
               value="{{ $contato->telefone }}"
               maxlength="9" onkeypress="return isNumberKey(event)"/>
         </div>
         <button type="submit" class="btn btn-primary">Alterar</button>
      </form>
   </div>
</div>
@endsection

resources/views/contato/index.blade.php
@extends('components.layout')
@section('header')
<div style="font-size:xx-large;color:white;margin-right:50%;">
   <span>Contatos&nbsp;listar</span>
</div>
@endsection
@section('content')
<style>
   .uper {
   margin-top: 40px;
   }
</style>
<div class="uper">
@if(session()->get('success'))
<div class="alert alert-success">
   {{ session()->get('success') }}  
</div>
<br />
@endif
@include('components.modal')
{{ $contatos->links() }}
<table class="table table-striped"  data-toggle="dataTable" data-form="deleteForm">
   <thead>
      <tr>
         <td>ID</td>
         <td>Cliente</td>
         <td>DDD</td>
         <td>Telefone</td>
         <td>&nbsp;</td>
         <td><a href="{{ route('contatos.create')}}" class="btn btn-outline-success btn-sm">
            <i class="fa fa-plus"></i>&nbsp;Adicionar</i></a>
         </td>
      </tr>
   </thead>
   <tbody>
      @foreach($contatos as $contato)       
      <tr>
         <td>{{$contato->id_contato}}</td>
         <td>{{$contato->nome}}</td>
         <td>{{$contato->ddd}}</td>
         <td>{{$contato->telefone}}</td>
         <td><a href="{{ route('contatos.edit', $contato->id_contato)}}" class="btn btn-outline-primary btn-sm">
            <i class="fa fa-edit"></i>&nbsp;Editar</i></a>
         </td>
         <td>
            <!-- <form action="{{ route('contatos.destroy', $contato->id_contato)}}" method="post">
               @csrf
               @method('DELETE')
               <button class="btn btn-outline-danger btn-sm" type="submit">Deletar</button>
               </form> -->
            <form method="POST" action="{{ route('contatos.destroy', $contato->id_contato) }}" class="form-inline form-delete">
               @csrf
               @method('DELETE')
               <hidden name="id" value="{{$contato->id_contato}}">
               <button type="submit" class="btn btn-outline-danger btn-sm" name="delete_modal" 
                  data-toggle="tooltip" title='Delete'><i class="fa fa-trash"></i>&nbsp;Deletar</button>
            </form>
         </td>
      </tr>
      @endforeach       
   </tbody>
</table>
<div>
@endsection