routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');


Route::get('/ajax', 'AjaxController@view');
Route::post('/ajax', 'AjaxController@send_http_request')->name('ajaxRequest.post');

Route::get('/getClientes', 'AjaxController@getClientes')->name('getClientes');
Route::post('/postClientes', 'AjaxController@postClientes')->name('postClientes');



Route::get('clientes/nomeTelefone', 'ClienteController@listNomeTelefone')->middleware('auth');
Route::get('clientes/nomeEndereco', 'ClienteController@listNomeEndereco')->middleware('auth');

Route::get('clientes/checkCEP', 'ClienteController@checkCEP')->middleware('auth');

Route::get('clientes/buscarNomeForm', 'ClienteController@buscarNomeForm')->middleware('auth');
Route::get('clientes/buscarNome', 'ClienteController@buscarNome')->middleware('auth');

Route::post('clientes/buscarNomeTelefone', 'ClienteController@buscarNomeTelefone')
            ->name('clientes.buscarNomeTelefone')->middleware('auth');
Route::post('clientes/buscarNome', 'ClienteController@buscarNome')
            ->name('clientes.buscarNome')->middleware('auth');          
            
            

Route::resource('cidades','CidadeController')->middleware('auth');

Route::resource('bairros','BairroController')->middleware('auth');

Route::resource('clientes','ClienteController')->middleware('auth');

Route::resource('contatos','ContatoController')->middleware('auth');

Route::resource('enderecos','EnderecoController')->middleware('auth');

/* quick and dirty
// dump sql query
// veja:https://stackoverflow.com/questions/27753868/how-to-get-the-query-executed-in-laravel-5-dbgetquerylog-returning-empty-ar
\Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {
    echo'<pre>';
    var_dump($query->sql);
    var_dump($query->bindings);
    var_dump($query->time);
    echo'</pre>';
});
*/

app/Cidade.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cidade extends Model
{
    // that does not work...why??
    protected $primaryKey = 'id_cidade';
    
    protected $fillable = array('nome', 'UF');    

    public $timestamps = false;

     
}

app/Http/Controllers/CidadeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CidadeController extends Controller
{    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {       
        $cidades = DB::table('cidades')
                   ->orderBy('nome')
                   ->paginate(10);      
        return view('cidade.index', ['cidades' => $cidades]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       // get all possible UFs from table
       // and pass to view      
       $ufs = DB::table('u_f_s')
                         ->select('UF','Estado')
                         ->orderBy('UF', 'asc')
                         ->get();       
       return view('cidade.create')->with(array('ufs'=>$ufs));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {       
        // sanitize 
        if ($request->UF == 'Escolher...') {
            $request->merge(array('UF' => ''));
        }
        $validatedData = $request->validate([
            'nome' => 'nullable',
            'UF' => 'nullable|max:2',           
        ]);
        $show = \App\Cidade::create($validatedData);   
        return redirect('/cidades')->with('success', 'Cidade foi gravada');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {                           
        $ufs = DB::table('u_f_s')
                         ->select('UF','Estado')
                         ->orderBy('UF', 'asc')
                         ->get();   
        $selectedUF = DB::table('cidades')
                         ->select('UF')                          
                         ->where('id_cidade',$id)
                         ->first()->UF;                         
        $cidade = \App\Cidade::where('id_cidade', $id)->first();       
        return view('cidade.edit', compact('cidade'))
                    ->with(array('ufs'=>$ufs))
                    ->with(array('selectedUF'=>$selectedUF));           
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {      
        $validatedData = $request->validate([
            'nome' => 'nullable',
            'UF' => 'nullable|max:2',           
        ]
        );      
        $nome = $validatedData["nome"];
        $UF = $validatedData["UF"];  
       
        DB::table('cidades')
            ->where('id_cidade', $id)
            ->update(['nome' => $nome,'UF' => $UF]);
       
        // \App\Cidade::whereId($id)->update($validatedData);        
        // does not work here cause Laravel assumes a field with name "id" as primaryKey
        // setting custom primaryKey in Model also does not work ...                       

        return redirect('/cidades')->with('success', 'Cidade foi alterada');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {                
        DB::table('cidades')
            ->where('id_cidade', $id)
            ->delete();       
        return redirect('/cidades')->with('success', 'Cidade foi deletada');
    }
}

resources/views/cidade/create.blade.php
@extends('components.layout')
@section('header')
<div style="font-size:xx-large;color:white;margin-right:50%;">
    <span>Cidades&nbsp;cadastrar</span>
</div>
@endsection
@section('content')
<style>
    .uper {
    margin-top: 40px;
    }
</style>
<div class="card uper">
    <div class="card-header">
        SAC - adicionar cidade
    </div>
    <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br />
        @endif
        <form name="storeCity" method="post" action="{{ route('cidades.store') }}">
            <div class="form-group">
                @csrf
                <label for="nome">Nome:</label>
                <input type="text" class="form-control" name="nome"/>
            </div>
            <div class="input-group mb-3">
                <select class="custom-select" id="UF" name="UF">
                    <option selected>Escolher...</option>
                    @foreach ($ufs as $uf)
                    <option value="{{ $uf->UF }}">{{ $uf->Estado }}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit" id="btn-submit" class="btn btn-primary">Adicionar</button>
        </form>
    </div>
</div>
@endsection

resources/views/cidade/edit.blade.php
@extends('components.layout')
@section('header')
<div style="font-size:xx-large;color:white;margin-right:50%;">
    <span>Cidades&nbsp;editar</span>
</div>
@endsection
@section('content')
<style>
    .uper {
    margin-top: 40px;
    }
</style>
<div class="card uper">
    <div class="card-header">
        Editar Cidade
    </div>
    <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br />
        @endif
        <form method="post" action="{{ route('cidades.update', $cidade->id_cidade ) }}">
            <div class="form-group">
                @csrf
                @method('PATCH')
                <label for="nome">Nome:</label>
                <input type="text" class="form-control" name="nome" value="{{ $cidade->nome }}"/>
            </div>
            <div class="input-group mb-3">
                <select class="custom-select" id="UF" name="UF">
                    <option selected>Escolher...</option>
                    @foreach ($ufs as $uf)                
                    <option  @if($selectedUF == $uf->UF) selected @endif
                    value="{{ $uf->UF }}">{{ $uf->Estado }}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Alterar</button>
        </form>
    </div>
</div>
@endsection

resources/views/cidade/index.blade.php
@extends('components.layout')
@section('header')
<div style="font-size:xx-large;color:white;margin-right:50%;">
    <span>Cidades&nbsp;listar</span>
</div>
@endsection
@section('content')
<style>
    .uper {
    margin-top: 40px;
    }
</style>
<div class="uper">
@if(session()->get('success'))
<div class="alert alert-success">
    {{ session()->get('success') }}  
</div>
<br />
@endif
@include('components.modal')
{{ $cidades->links() }}
<table class="table table-striped" data-toggle="dataTable" data-form="deleteForm">
    <thead>
        <tr>
            <!-- <td>ID</td> -->
            <td>Cidade</td>
            <td>UF</td>
            <td>&nbsp;</td>
            <td><a href="{{ route('cidades.create')}}" class="btn btn-outline-success btn-sm"><i class="fa fa-plus"></i>&nbsp;Adicionar</a></td>
        </tr>
    </thead>
    <tbody>
        @foreach($cidades as $cidade)       
        <tr>
            <!-- <td>{{$cidade->id_cidade}}</td> -->
            <td>{{$cidade->nome}}</td>
            <td>{{$cidade->UF}}</td>
            <td><a href="{{ route('cidades.edit', $cidade->id_cidade)}}" class="btn btn-outline-primary btn-sm"> <i class="fa fa-edit"></i>&nbsp;Editar</a></td>
            <td>
                <!--  <form action="{{ route('cidades.destroy', $cidade->id_cidade)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-outline-danger btn-sm" type="submit">Deletar</button>
                    </form>  -->
                <form method="POST" action="{{ route('cidades.destroy', $cidade->id_cidade) }}" class="form-inline form-delete">
                    @csrf
                    @method('DELETE')
                    <hidden name="id" value="{{$cidade->id_cidade}}">
                    <button type="submit" class="btn btn-outline-danger btn-sm" name="delete_modal" 
                        data-toggle="tooltip" title='Delete'><i class="fa fa-trash"></i>&nbsp;Deletar</button>
                </form>
            </td>
        </tr>
        @endforeach       
    </tbody>
</table>
<div>
<!-- TEST -->
@endsection