routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');


Route::get('/ajax', 'AjaxController@view');
Route::post('/ajax', 'AjaxController@send_http_request')->name('ajaxRequest.post');

Route::get('/getClientes', 'AjaxController@getClientes')->name('getClientes');
Route::post('/postClientes', 'AjaxController@postClientes')->name('postClientes');



Route::get('clientes/nomeTelefone', 'ClienteController@listNomeTelefone')->middleware('auth');
Route::get('clientes/nomeEndereco', 'ClienteController@listNomeEndereco')->middleware('auth');

Route::get('clientes/checkCEP', 'ClienteController@checkCEP')->middleware('auth');

Route::get('clientes/buscarNomeForm', 'ClienteController@buscarNomeForm')->middleware('auth');
Route::get('clientes/buscarNome', 'ClienteController@buscarNome')->middleware('auth');

Route::post('clientes/buscarNomeTelefone', 'ClienteController@buscarNomeTelefone')
            ->name('clientes.buscarNomeTelefone')->middleware('auth');
Route::post('clientes/buscarNome', 'ClienteController@buscarNome')
            ->name('clientes.buscarNome')->middleware('auth');          
            
            

Route::resource('cidades','CidadeController')->middleware('auth');

Route::resource('bairros','BairroController')->middleware('auth');

Route::resource('clientes','ClienteController')->middleware('auth');

Route::resource('contatos','ContatoController')->middleware('auth');

Route::resource('enderecos','EnderecoController')->middleware('auth');

/* quick and dirty
// dump sql query
// veja:https://stackoverflow.com/questions/27753868/how-to-get-the-query-executed-in-laravel-5-dbgetquerylog-returning-empty-ar
\Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {
    echo'<pre>';
    var_dump($query->sql);
    var_dump($query->bindings);
    var_dump($query->time);
    echo'</pre>';
});
*/

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $primaryKey = 'id_cliente';
    
    protected $fillable = array('nome','tipo_pessoa','cpf_cnpj','email');    

    public $timestamps = false;
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ClienteController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {       
        $clientes = DB::table('clientes')
                   ->orderBy('nome')
                   ->paginate(10);      
        return view('cliente.index', ['clientes' => $clientes]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {             
       return view('cliente.create');
    }

     /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {    
        // sanitize 
        if ($request->tipo_pessoa == 'Escolher...') {
            $request->merge(array('tipo_pessoa' => 'X'));
        }
        // determines location of redirect
        $hidden = $request->request->get('hidden'); 
        
        $validatedData = $request->validate([
            'nome' => 'nullable',
            'tipo_pessoa' => 'nullable|max:1',     
            'cpf_cnpj' => 'nullable|cpf|unique:clientes',
            'email' => 'nullable|email'      
        ]
        ,['cpf_cnpj' =>' O CPF/CNPF já está sendo utilizado.']     
        );
        $show = \App\Cliente::create($validatedData);   
        
         // voltar para show
         if (!is_null($hidden)) {
            return redirect('/clientes/'.$show->id_cliente);
        }
        // voltar para clientes.index
        return redirect('/clientes')->with('success', 'Cliente foi gravado');              
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {                                  
        $cliente = \App\Cliente::where('id_cliente', $id)->first();       
        return view('cliente.edit', compact('cliente'));           
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {      
        $validatedData = $request->validate([
            'nome' => 'nullable',
            'tipo_pessoa' => 'required|max:1',     
            'cpf_cnpj' => 'nullable|cpf',
            'email' => 'nullable|email'      
        ]   
        ,['cpf_cnpj' =>' O CPF/CNPF já está sendo utilizado.']              
        ); 
        $nome = $validatedData["nome"];
        $tipo_pessoa = $validatedData["tipo_pessoa"];
        $cpf_cnpj = $validatedData["cpf_cnpj"];
        $email = $validatedData["email"];
       
       
        DB::table('clientes')
            ->where('id_cliente', $id)
            ->update([
                'nome' => $nome,
                'tipo_pessoa' => $tipo_pessoa,
                'cpf_cnpj' => $cpf_cnpj,
                'email' => $email,
                ]);
       
        // \App\Cidade::whereId($id)->update($validatedData);        
        // does not work here cause Laravel assumes a field with name "id" as primaryKey
        // setting custom primaryKey in Model also does not work ...                       

        return redirect('/clientes')->with('success', 'Cliente foi alterada');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {                
        DB::table('clientes')
            ->where('id_cliente', $id)
            ->delete();       
        return redirect('/clientes')->with('success', 'Cliente foi deletada');
    }

    /**
     * Listagem com nome e telefone
     */
    public function listNomeTelefone()
    {
        $clientes = DB::table('clientes')
                   ->join('contatos', 'contatos.cliente_id_cliente', '=', 'clientes.id_cliente')  
                   ->select('nome','ddd','telefone','id_cliente')
                   ->orderBy('nome')
                   ->orderBy('ddd')
                   ->orderBy('telefone')
                   ->paginate(10);             
        return view('cliente.nomeTelefone', ['clientes' => $clientes]);
    }

     /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function show($id)
     {        
        $clientes = DB::table('clientes')                    
                    ->select('id_cliente', 'nome', 'tipo_pessoa', 'cpf_cnpj', 'email')
                    ->where('id_cliente',$id)->first();
        $telefones = DB::table('contatos')                    
                    ->select('id_contato', 'cliente_id_cliente', 'ddd', 'telefone')
                    ->where('cliente_id_cliente',$id)->get();   
        $enderecos  = DB::table('enderecos')  
                     ->join('bairros','enderecos.bairro_id_bairro','=','bairros.id_bairro')
                     ->join('cidades', 'bairros.cidade_id_cidade', '=', 'cidades.id_cidade')                  
                    ->select('id_endereco', 'bairro_id_bairro', 'cliente_id_cliente', 'cep', 'logradouro','numero','complemento',
                             'id_bairro','cidade_id_cidade', 'bairros.nome as bnome',
                             'id_cidade','cidades.nome as cnome','UF')
                    ->where('cliente_id_cliente',$id)->get();                       

        return view('cliente.show', ['clientes' => $clientes, 'telefones' => $telefones, 'enderecos'=> $enderecos]);
     }
    /**
     * Listagem com nome e telefone
     */
    public function buscarNomeTelefone(Request $request)
    {
        $telefone = $request->input('telefone');

        $raw  = "";
        $raw .= "SELECT id_cliente, id_contato, nome, ddd, telefone FROM clientes cl, contatos co ";
        $raw .= "WHERE cl.id_cliente = co.cliente_id_cliente ";
        $raw .= "AND telefone LIKE '%".$telefone."%' ";
        $raw .= "ORDER BY nome, ddd, telefone";

        // raw query faster, but without pagination
        $clientes = DB::select($raw);
                         
        return view('cliente.nomeTelefone', ['clientes' => $clientes]);
    }

    /**
     * Listagem com nome e endereco
     */
    public function listNomeEndereco()
    {
        $clientes = DB::table('clientes')
                   ->join('enderecos', 'enderecos.cliente_id_cliente', '=', 'clientes.id_cliente')  
                   ->join('bairros', 'enderecos.bairro_id_bairro', '=', 'bairros.id_bairro')
                   ->join('cidades', 'bairros.cidade_id_cidade', '=', 'cidades.id_cidade')
                   ->select('clientes.nome as clientes_nome','cep',
                            'cidades.nome as cidades_nome',
                            'bairros.nome as bairros_nome',
                            'logradouro','numero','complemento',
                            'clientes.id_cliente'
                            )
                   ->orderBy('clientes.nome')
                   ->orderBy('cidades.nome')
                   ->orderBy('bairros.nome')

                   ->paginate(10);             
        return view('cliente.nomeEndereco', ['clientes' => $clientes]);
    }

    /**
     * Busca por nome formulario
     */
    public function buscarNomeForm() {
       
        return view('cliente.buscarNomeForm');
    }
    /**
     * Busca por nome
     */
    public function buscarNome(Request $request) {
       
        $start = microtime(true);
        $nome = $request->nome;

        $clientes = DB::table('clientes')
                    ->select('id_cliente','nome')
                    ->where('nome','like','%'.$nome.'%')
                    ->orderBy('nome')                   
                    ->paginate(20);
                    //->paginate(20)->dump();
       
        return view('cliente.buscarNomeForm', ['clientes' => $clientes]);
    }
    /**
     * Teste webservice VIACEP
     */
    public function checkCEP() {
        $cep = '44190000';
        $cep = '44190001';
        $cep = preg_replace("/[^0-9]/", "", $cep);
        $url = "http://viacep.com.br/ws/$cep/xml/";

        $xml = simplexml_load_file($url);
        var_dump($xml);
        print_r($xml->localidade);
        print_r(gettype($xml->localidade));  
        print_r($xml->uf == "BA");

        $ba = strval($xml->uf);
        print_r(gettype($ba)); 

        $ddd = strval($xml->ddd);
        $localidade = strval($xml->localidade);
        $uf = strval($xml->uf);
        $logradouro = strval($xml->logradouro);
        $complemento = strval($xml->complemento);

        $bairro = strval($xml->bairro);

        print_r( gettype($bairro)) ;
        print_r(strlen($bairro));

        $erro = strval($xml->erro);
        if ($erro == "true") print_r("TRUE");

        dd($xml);
        return view('home');
    }
}

resources/views/cliente/buscarNomeForm.blade.php
@extends('components.layout')

@section('header')
<div style="font-size:xx-large;color:white;margin-right:50%;">
<span>Clientes&nbsp;buscar</span>
</div>
@endsection

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
  .card-columns {
        column-count: 1;
  } 
  
</style>

<div class="uper">
@isset($clientes)
 @if( $clientes instanceof \Illuminate\Pagination\LengthAwarePaginator )
   {{ $clientes->links() }}
 @endif
@endisset
  <div class="container">

   <div class="card-columns">
                     
      <!-- CLIENTE --> 
      <div class="card-header">Cliente</div>
      <div class="card bg-light">
          <div class="card-body">            
            <form action="{{ route('clientes.buscarNome') }}"   method="post" role="search">    
                @csrf   
                <div class="input-group">
                    <input type="text" class="form-control" name="nome" id="nome"
                        placeholder="buscar nome"> <span class="input-group-btn">
                        <button type="submit" class="btn btn-outline-primary">                     
                        <a href="{{ url('/') }}/clientes/buscarNome"><p class="card-text">Reset</p></a>      
                        </button> 
                        <button type="submit" class="btn btn-outline-primary"> 
                        Buscar nome          
                        </button>
                    </span>
                </div>
            </form>
          </div> 
          </div>
          </div> 

      <div class="card-header">Resultados</div>
       <div class="card bg-light">
          <div class="card-body">
            @isset($clientes)
            <div class="container">
            
            @foreach($clientes as $cliente)
               <div class="row">
                <div class="col-sm-12"><a href="{{ url('/') }}/clientes/{{$cliente->id_cliente}}">{{$cliente->nome}}</a></div>   
               </div>
            @endforeach    
            </div> <!-- container -->                           
            @endisset
       </div>
      </div>              
          </div>
      </div>
  </div> <!-- end container -->
    
<div>
@endsection

resources/views/cliente/create.blade.php
@extends('components.layout')
@section('header')
<div style="font-size:xx-large;color:white;margin-right:50%;">
   <span>Clientes&nbsp;cadastrar</span>
</div>
@endsection
@section('content')
<style>
   .uper {
   margin-top: 40px;
   }
</style>
<div class="card uper">
   <div class="card-header">
      SAC - adicionar cliente
   </div>
   <div class="card-body">
      @if ($errors->any())
      <div class="alert alert-danger">
         <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
         </ul>
      </div>
      <br />
      @endif
      <!-- necessary for redirection-->
      @php     
      $url = session()->all()['_previous']['url'] ;   
      $fromNovoCliente = strpos( $url,'clientes') == false ;     
      if($errors->any()) {      
      $isHidden =  isset( session()->all()['_old_input']['hidden'] );
      if ($isHidden) {
      $fromNovoCliente= true;
      }            
      }
      @endphp
      <form method="post" action="{{ route('clientes.store') }}" onsubmit="clearCpfCnpj()">
         <div class="form-group">
            @csrf
            <!-- pass id do novo cliente to endereco.store -->
            @if($fromNovoCliente)
            <input name="hidden" type="hidden" value="dummy"/> 
            @endif              
            <label for="nome">Nome:</label>
            <input type="text" class="form-control" name="nome" 
            @if($errors->any()) value="{{session()->all()['_old_input']['nome'] }}" @endif
            />
         </div>
         <label for="tipo_pessoa">Tipo Pessoa: o sistema vai informar automaticamente caso achar CPF/CNPJ válido</label>
         <div class="input-group mb-3">
            <select class="custom-select" id="tipo_pessoa" name="tipo_pessoa">
               <option selected>Escolher...</option>
               <option
               @if($errors->any() && session()->all()['_old_input']['tipo_pessoa'] == 'F' ) 
               selected
               @endif 
               value="F">Pessoa Física</option>
               <option
               @if($errors->any() && session()->all()['_old_input']['tipo_pessoa'] == 'J' ) 
               selected
               @endif 
               value="J">Pessoa Jurídica</option>
            </select>
         </div>
         <div class="form-group">
            <label for="cpf_cnpj">CPF/CPNJ: só precisa informar digitos CPF(11) / CNPJ(14)</label>
            <!--HTML5 pattern not appropriate here-->
            <input type="text" class="form-control"  id="cpf_cnpj" name="cpf_cnpj"
            @if($errors->any()) value="{{session()->all()['_old_input']['cpf_cnpj'] }}" @endif
            onkeypress="return isNumberKey(event)"/>              
         </div>
         <div class="form-group">              
            <label for="email">Email:</label>
            <input type="text" class="form-control" name="email"
            @if($errors->any()) value="{{session()->all()['_old_input']['email'] }}" @endif
            />              
         </div>
         <button type="submit" class="btn btn-primary">Adicionar</button>
      </form>
   </div>
</div>
@endsection

resources/views/cliente/edit.blade.php
@extends('components.layout')
@section('header')
<div style="font-size:xx-large;color:white;margin-right:50%;">
   <span>Clientes&nbsp;editar</span>
</div>
@endsection
@section('content')
<style>
   .uper {
   margin-top: 40px;
   }
</style>
<div class="card uper">
   <div class="card-header">
      Editar Cliente
   </div>
   <div class="card-body">
      @if ($errors->any())
      <div class="alert alert-danger">
         <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
         </ul>
      </div>
      <br />
      @endif
      <form method="post" action="{{ route('clientes.update', $cliente->id_cliente ) }}" onsubmit="clearCpfCnpj()">
         <div class="form-group">
            @csrf
            @method('PATCH')
            <label for="nome">Nome:</label>
            <input type="text" class="form-control" name="nome" value="{{ $cliente->nome }}"/>
         </div>
         <label for="tipo_pessoa">Tipo Pessoa: o sistema vai informar automaticamente caso achar CPF/CNPJ válido</label>
         <div class="input-group mb-3">          
            <select class="custom-select" id="tipo_pessoa" name="tipo_pessoa">  
            <option @if($cliente->tipo_pessoa == 'X') selected @endif value="X">Escolher...</option>                                 
            <option @if($cliente->tipo_pessoa == 'F') selected @endif value="F">Pessoa Física</option>
            <option @if($cliente->tipo_pessoa == 'J') selected @endif value="J">Pessoa Jurídica</option>
            </select>
         </div>
         <div class="form-group">              
            <label for="cpf_cnpj">CPF/CPNJ: só precisa informar digitos CPF(11) / CNPJ(14)</label>
            <input type="text" class="form-control" id="cpf_cnpj" name="cpf_cnpj"  
               value="{{ Helper::formatCnpjCpf($cliente->cpf_cnpj) }}"
               onkeypress="return isNumberKey(event)"/>             
         </div>
         <div class="form-group">              
            <label for="email">Email:</label>
            <input type="text" class="form-control" name="email" value="{{ $cliente->email }}"/>             
         </div>
         <button type="submit" class="btn btn-primary">Alterar</button>
      </form>
   </div>
</div>
@endsection

resources/views/cliente/index.blade.php
@extends('components.layout')
@section('header')
<div style="font-size:xx-large;color:white;margin-right:50%;">
   <span>Clientes&nbsp;listar</span>
</div>
@endsection
@section('content')
<style>
   .uper {
   margin-top: 40px;
   }
</style>
<div class="uper">
@if(session()->get('success'))
<div class="alert alert-success">
   {{ session()->get('success') }}  
</div>
<br />
@endif
@include('components.modal')
{{ $clientes->links() }}
<table class="table table-striped" data-toggle="dataTable" data-form="deleteForm">
   <thead>
      <tr>
         <td>Nome</td>
         <td>Tipo Pessoa</td>
         <td>CPF/CNPJ</td>
         <td>Email</td>
         <td>&nbsp;</td>
         <td><a href="{{ route('clientes.create')}}" class="btn btn-outline-success btn-sm"><i class="fa fa-plus"></i>&nbsp;Adicionar</i></a></td>
      </tr>
   </thead>
   <tbody>
      @foreach($clientes as $cliente)       
      <tr>
         <td>{{$cliente->nome}}</td>
         <td>
            @if($cliente->tipo_pessoa == 'J')
            Pessoa Jurídica
            @endif 
            @if($cliente->tipo_pessoa == 'F')          
            Pessoa Física     
            @endif
         </td>
         <!-- Helper method to format Cpf/Cnpj -->
         <td>{{Helper::formatCnpjCpf($cliente->cpf_cnpj)}}</td>
         <td>{{$cliente->email}}</td>
         <td><a href="{{ route('clientes.edit', $cliente->id_cliente)}}" class="btn btn-outline-primary btn-sm"><i class="fa fa-edit"></i>&nbsp;</i>Editar</a></td>
         <td>
            <!-- <form action="{{ route('clientes.destroy', $cliente->id_cliente)}}" method="post">
               @csrf
               @method('DELETE')
               <button class="btn btn-outline-danger btn-sm" type="submit">Deletar</button>
               </form> -->
            <form method="POST" action="{{ route('clientes.destroy', $cliente->id_cliente) }}" class="form-inline form-delete">
               @csrf
               @method('DELETE')
               <hidden name="id" value="{{$cliente->id_cliente}}">
               <button type="submit" class="btn btn-outline-danger btn-sm" name="delete_modal" 
                  data-toggle="tooltip" title='Delete'><i class="fa fa-trash"></i>&nbsp;Deletar</button>
            </form>
         </td>
      </tr>
      @endforeach       
   </tbody>
</table>
<div>
@endsection

resources/views/cliente/nomeEndereco.blade.php
@extends('components.layout')
@section('header')
<div style="font-size:xx-large;color:white;margin-right:30%;">
   <span>Listagem com nome e endereço</span>
</div>
@endsection
@section('content')
<style>
   .uper {
   margin-top: 40px;
   }
</style>
<div class="uper">
@if(session()->get('success'))
<div class="alert alert-success">
   {{ session()->get('success') }}  
</div>
<br />
@endif
{{ $clientes->links() }}
<table class="table table-striped">
   <thead>
      <tr>
         <td>Cliente</td>
         <td>CEP</td>
         <td>Cidade</td>
         <td>Bairro</td>
         <td>Logradouro</td>
         <td>Numero</td>
         <td>Complemento</td>
      </tr>
   </thead>
   <tbody>
      @foreach($clientes as $cliente)       
      <tr>
         <td><a href="{{ url('/') }}/clientes/{{$cliente->id_cliente}}">{{$cliente->clientes_nome}}</a></td>
         <td>{{Helper::formatCEP($cliente->cep)}} </td>
         <td>{{$cliente->cidades_nome}}</td>
         <td>{{$cliente->bairros_nome}}</td>
         <td>{{$cliente->logradouro}}</td>
         <td>{{$cliente->numero}}</td>
         <td>{{$cliente->complemento}}</td>
      </tr>
      @endforeach       
   </tbody>
</table>
<div>
@endsection

resources/views/cliente/nomeTelefone.blade.php
@extends('components.layout')
@section('header')
<div style="font-size:xx-large;color:white;margin-right:30%;">
   <span>Listagem com nome e telefone</span>
</div>
@endsection
@section('content')
<style>
   .uper {
   margin-top: 40px;
   }
</style>
<div class="uper">
@if(session()->get('success'))
<div class="alert alert-success">
   {{ session()->get('success') }}  
</div>
<br />
@endif
<form action="{{ route('clientes.buscarNomeTelefone') }}"   method="post" role="search">
   @csrf   
   <div class="input-group">
      <input type="text" class="form-control" name="telefone" id="telefone"
         placeholder="buscar telefones"> 
      <span class="input-group-btn">
         <button type="submit" class="btn btn-outline-primary">
            <a href="{{ url('/') }}/clientes/nomeTelefone">
               <p class="card-text">Reset</p>
            </a>
         </button>
         <button type="submit" class="btn btn-outline-primary"> 
         Buscar telefone              
         </button>
      </span>
   </div>
</form>
<br />
@if( $clientes instanceof \Illuminate\Pagination\LengthAwarePaginator )
{{ $clientes->links() }}
@endif
<table class="table table-striped">
   <thead>
      <tr>
         <td>Nome</td>
         <td>DDD</td>
         <td>Telefone</td>
      </tr>
   </thead>
   <tbody>
      @foreach($clientes as $cliente)       
      <tr>
         <td><a href="{{ url('/') }}/clientes/{{$cliente->id_cliente}}">{{$cliente->nome}}</a></td>
         <td>{{$cliente->ddd}}</td>
         <td>{{$cliente->telefone}}</td>
      </tr>
      @endforeach       
   </tbody>
</table>
<div>
@endsection

resources/views/cliente/show.blade.php
@extends('components.layout')
@section('header')
<div style="font-size:xx-large;color:white;margin-right:50%;">
   <span>&nbsp;{{$clientes->nome}}</span>
</div>
@endsection
@section('content')
<style>
   .uper {
   margin-top: 40px;
   }
   .card-columns {
   column-count: 1;
   } 
</style>
<div class="uper">
<div class="container">
<div class="card-columns">
   <!-- CLIENTE --> 
   <div class="card-header"><b>Cliente</b></div>
   <div class="card bg-light">
      <div class="card-body">
         <dicv class="container">
         <div class="row">
            <div class="col-sm-3">nome</div>
            <div class="col-sm-9">{{ $clientes->nome}}</div>
         </div>
         <div class="row">
            <div class="col-sm-3">tipo de pessoa</div>
            <div class="col-sm-9">
               @if( $clientes->tipo_pessoa == 'F') pessoa física @endif
               @if( $clientes->tipo_pessoa == 'J') pessoa jurídica @endif
            </div>
         </div>
         <div class="row">
            <div class="col-sm-3">cpf/cnpj</div>
            <div class="col-sm-9">{{ Helper::formatCnpjCpf($clientes->cpf_cnpj) }}</div>
         </div>
         <div class="row">
            <div class="col-sm-3">email</div>
            <div class="col-sm-9">{{ $clientes->email }}</div>
         </div>
      </div>
   </div>
</div>
<!-- CONTATOS (TELEFONES) -->
<div class="card-header"><b>Contatos&nbsp;&nbsp;&nbsp;</b> 
                         <a href="{{ route('contatos.create') }}" class="btn btn-outline-success btn-sm">
                         <i class="fa fa-plus"></i>&nbsp;Adicionar</i></a></div>
<div class="card bg-light">
   <div class="card-body">
      <div class="container">
         @foreach($telefones as $telefone) 
         <div class="row">
            <div class="col-sm-9">{{ Helper::formatTelefone($telefone->ddd.$telefone->telefone)}}</div>
         </div>
         @endforeach    
      </div>
   </div>
   <!-- ENDERECOS -->
   <div class="card-header"><b>Endereços&nbsp;&nbsp;</b><a href="{{ route('enderecos.create') }}" class="btn btn-outline-success btn-sm">
                            <i class="fa fa-plus"></i>&nbsp;Adicionar</a></a></div>
   <div class="card bg-light">
      <div class="card-body">
         <div class="container">
            <div class="row" style="font-weight:bold">
               <div class="col-sm-2">cep</div>
               <div class="col-sm-2">cidade</div>
               <div class="col-sm-2">bairro</div>
               <div class="col-sm-2">logradouro</div>
               <div class="col-sm-2">numero</div>
               <div class="col-sm-2">complemento</div>
            </div>
            @foreach($enderecos as $endereco) 
            <div class="row">
               <div class="col-sm-2">{{ Helper::formatCEP($endereco->cep)}} </div>
               <div class="col-sm-2">{{ $endereco->cnome}} </div>
               <div class="col-sm-2">{{ $endereco->bnome}} </div>
               <div class="col-sm-2">{{ $endereco->logradouro}} </div>
               <div class="col-sm-2">{{ $endereco->numero}} </div>
               <div class="col-sm-2">{{ $endereco->complemento}} </div>
            </div>
            @endforeach    
         </div>
      </div>
   </div>
</div>
<div>
@endsection