routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');


Route::get('/ajax', 'AjaxController@view');
Route::post('/ajax', 'AjaxController@send_http_request')->name('ajaxRequest.post');

Route::get('/getClientes', 'AjaxController@getClientes')->name('getClientes');
Route::post('/postClientes', 'AjaxController@postClientes')->name('postClientes');



Route::get('clientes/nomeTelefone', 'ClienteController@listNomeTelefone')->middleware('auth');
Route::get('clientes/nomeEndereco', 'ClienteController@listNomeEndereco')->middleware('auth');

Route::get('clientes/checkCEP', 'ClienteController@checkCEP')->middleware('auth');

Route::get('clientes/buscarNomeForm', 'ClienteController@buscarNomeForm')->middleware('auth');
Route::get('clientes/buscarNome', 'ClienteController@buscarNome')->middleware('auth');

Route::post('clientes/buscarNomeTelefone', 'ClienteController@buscarNomeTelefone')
            ->name('clientes.buscarNomeTelefone')->middleware('auth');
Route::post('clientes/buscarNome', 'ClienteController@buscarNome')
            ->name('clientes.buscarNome')->middleware('auth');          
            
            

Route::resource('cidades','CidadeController')->middleware('auth');

Route::resource('bairros','BairroController')->middleware('auth');

Route::resource('clientes','ClienteController')->middleware('auth');

Route::resource('contatos','ContatoController')->middleware('auth');

Route::resource('enderecos','EnderecoController')->middleware('auth');

/* quick and dirty
// dump sql query
// veja:https://stackoverflow.com/questions/27753868/how-to-get-the-query-executed-in-laravel-5-dbgetquerylog-returning-empty-ar
\Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {
    echo'<pre>';
    var_dump($query->sql);
    var_dump($query->bindings);
    var_dump($query->time);
    echo'</pre>';
});
*/

app/Bairro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bairro extends Model
{
    protected $primaryKey = 'id_bairro';
    protected $fillable = [
        'cidade_id_cidade','nome'
    ];
    public $timestamps = false;
}

app/Http/Controllers/BairroController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BairroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {       
       
        $bairros = DB::table('bairros')
                   ->join('cidades','bairros.cidade_id_cidade','=','cidades.id_cidade') 
                   ->select('bairros.id_bairro','bairros.nome','bairros.cidade_id_cidade','cidades.nome as cnome')
                   ->orderBy('bairros.nome')                                  
                   ->paginate(10);                         
        return view('bairro.index', ['bairros' => $bairros]);
    }

     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {             
       $cidades = DB::table('cidades')
                         ->select('nome','id_cidade')
                         ->orderBy('nome', 'asc')
                         ->get();       
       return view('bairro.create')->with(array('cidades'=>$cidades));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {               
      
        $validatedData = $request->validate([
            'nome' => 'nullable',   
            'cidade_id_cidade' => 'required|numeric'            
        ]       
        ,['Favor, escolher cidade!']     
        );
        $show = \App\Bairro::create($validatedData);   
        
        return redirect('/bairros')->with('success', 'Bairro foi gravada');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {                           
        $cidades = DB::table('cidades')
                         ->select('nome','id_cidade')
                         ->orderBy('nome', 'asc')
                         ->get();     
        $selectedCidade = DB::table('bairros')
                         ->select('cidade_id_cidade')                          
                         ->where('id_bairro',$id)
                         ->first()->cidade_id_cidade;                                  
        $bairro = \App\Bairro::where('id_bairro', $id)->first();       
        return view('bairro.edit', compact('bairro'))
                    ->with(array('cidades'=>$cidades))          
                    ->with(array('selectedCidade'=>$selectedCidade)); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {      
        $validatedData = $request->validate([
            'nome' => 'nullable',   
            'cidade_id_cidade' => 'required|numeric'           
        ]       
        ,['Favor, escolher cidade!']       
        );
        $nome = $validatedData["nome"];
        $cidade_id_cidade = $validatedData["cidade_id_cidade"];  
       
        DB::table('bairros')
            ->where('id_bairro', $id)
            ->update(['nome' => $nome,'cidade_id_cidade' => $cidade_id_cidade]);
       
        // \App\Cidade::whereId($id)->update($validatedData);        
        // does not work here cause Laravel assumes a field with name "id" as primaryKey
        // setting custom primaryKey in Model also does not work ...                       

        return redirect('/bairros')->with('success', 'Bairro foi alterada');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {                
        DB::table('bairros')
            ->where('id_bairro', $id)
            ->delete();       
        return redirect('/bairros')->with('success', 'Bairro foi deletada');
    }
}

resources/views/bairro/create.blade.php
@extends('components.layout')
@section('header')
<div style="font-size:xx-large;color:white;margin-right:50%;">
   <span>Bairros&nbsp;cadastrar</span>
</div>
@endsection
@section('content')
<style>
   .uper {
   margin-top: 40px;
   }
</style>
<div class="card uper">
   <div class="card-header">
      SAC - adicionar bairro
   </div>
   <div class="card-body">
      @if ($errors->any())
      <div class="alert alert-danger">
         <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
         </ul>
      </div>
      <br />
      @endif

      <form  method="post" action="{{ route('bairros.store') }}">
         <div class="form-group">
            @csrf
            <label for="nome">Nome:</label>
            <!-- null coalescing o nome -->
            <input type="text" class="form-control" name="nome" value="{{session()->all()['_old_input']['nome'] ?? ''}}"/>
         </div>
         <div class="input-group mb-3">
            <select class="custom-select" id="cidade_id_cidade" name="cidade_id_cidade">
               <option selected>Escolher cidade...</option>
               @foreach ($cidades as $cidade)
                 <option value="{{ $cidade->id_cidade }}">{{ $cidade->nome }}</option>
               @endforeach
            </select>
         </div>
         <button type="submit" class="btn btn-primary">Adicionar</button>
      </form>
   </div>
</div>
@endsection

resources/views/bairro/edit.blade.php
@extends('components.layout')
@section('header')
<div style="font-size:xx-large;color:white;margin-right:50%;">
   <span>Bairros&nbsp;editar</span>
</div>
@endsection
@section('content')
<style>
   .uper {
   margin-top: 40px;
   }
</style>
<div class="card uper">
   <div class="card-header">
      Editar Bairro
   </div>
   <div class="card-body">
      @if ($errors->any())
      <div class="alert alert-danger">
         <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
         </ul>
      </div>
      <br />
      @endif
      <form method="post" action="{{ route('bairros.update', $bairro->id_bairro ) }}">
         <div class="form-group">
            @csrf
            @method('PATCH')
            <label for="nome">Nome:</label>
            <input type="text" class="form-control" name="nome" value="{{ $bairro->nome }}"/>
         </div>
         <div class="input-group mb-3">
            <select class="custom-select" id="cidade_id_cidade" name="cidade_id_cidade">
               <option selected>Escolher cidade...</option>
               @foreach ($cidades as $cidade)
               <option 
               @if($selectedCidade == $cidade->id_cidade) selected @endif
               value="{{ $cidade->id_cidade }}">{{ $cidade->nome }}</option>
               @endforeach
            </select>
         </div>
         <button type="submit" class="btn btn-primary">Alterar</button>
      </form>
   </div>
</div>
@endsection

resources/views/bairro/index.blade.php
@extends('components.layout')
@section('header')
<div style="font-size:xx-large;color:white;margin-right:50%;">
   <span>Bairros&nbsp;listar</span>
</div>
@endsection
@section('content')
<style>
   .uper {
   margin-top: 40px;
   }
</style>
<div class="uper">
@if(session()->get('success'))
<div class="alert alert-success">
   {{ session()->get('success') }}  
</div>
<br />
@endif
@include('components.modal')
{{ $bairros->links() }}
<table class="table table-striped" data-toggle="dataTable" data-form="deleteForm">
   <thead>
      <tr>
         <td>Bairro</td>
         <td>Cidade</td>
         <td>&nbsp;</td>
         <td><a href="{{ route('bairros.create')}}" class="btn btn-outline-success btn-sm"><i class="fa fa-plus"></i>&nbsp;Adicionar</a></td>
      </tr>
   </thead>
   <tbody>
      @foreach($bairros as $bairro)       
      <tr>
         <td>{{$bairro->nome}}</td>
         <td>{{$bairro->cnome}}</td>
         <td><a href="{{ route('bairros.edit', $bairro->id_bairro)}}" class="btn btn-outline-primary btn-sm"><i class="fa fa-edit"></i>&nbsp;Editar</a></td>
         <td>
            <form action="{{ route('bairros.destroy', $bairro->id_bairro)}}" method="post" class="form-inline form-delete">
               @csrf
               @method('DELETE')
               <hidden name="id" value="{{$bairro->id_bairro}}">
               <button type="submit" class="btn btn-outline-danger btn-sm" name="delete_modal" 
                  data-toggle="tooltip" title='Delete'><i class="fa fa-trash"></i>&nbsp;Deletar</button>
            </form>
         </td>
      </tr>
      @endforeach       
   </tbody>
</table>
<div>
@endsection